language: python
cache: pip

matrix:
  include:
    # Wagtail 1.8
    - env: TOXENV=py27-dj18-wt18
      python: 2.7
    - env: TOXENV=py34-dj18-wt18
      python: 3.4
    - env: TOXENV=py35-dj18-wt18
      python: 3.5
    - env: TOXENV=py27-dj110-wt18
      python: 2.7
    - env: TOXENV=py34-dj110-wt18
      python: 3.4
    - env: TOXENV=py35-dj110-wt18
      python: 3.5

      # Wagtail 1.9
    - env: TOXENV=py27-dj18-wt19
      python: 2.7
    - env: TOXENV=py34-dj18-wt19
      python: 3.4
    - env: TOXENV=py35-dj18-wt19
      python: 3.5
    - env: TOXENV=py27-dj110-wt19
      python: 2.7
    - env: TOXENV=py34-dj110-wt19
      python: 3.4
    - env: TOXENV=py35-dj110-wt19
      python: 3.5

    # Wagtail 1.10
    - env: TOXENV=py27-dj18-wt110
      python: 2.7
    - env: TOXENV=py34-dj18-wt110
      python: 3.4
    - env: TOXENV=py35-dj18-wt110
      python: 3.5
    - env: TOXENV=py27-dj110-wt110
      python: 2.7
    - env: TOXENV=py34-dj110-wt110
      python: 3.4
    - env: TOXENV=py35-dj110-wt110
      python: 3.5
    - env: TOXENV=py27-dj111-wt110
      python: 2.7
    - env: TOXENV=py34-dj111-wt110
      python: 3.4
    - env: TOXENV=py35-dj111-wt110
      python: 3.5

    # Wagtail 1.11
    - env: TOXENV=py27-dj18-wt111
      python: 2.7
    - env: TOXENV=py34-dj18-wt111
      python: 3.4
    - env: TOXENV=py35-dj18-wt111
      python: 3.5
    - env: TOXENV=py27-dj110-wt111
      python: 2.7
    - env: TOXENV=py34-dj110-wt111
      python: 3.4
    - env: TOXENV=py35-dj110-wt111
      python: 3.5
    - env: TOXENV=py27-dj111-wt111
      python: 2.7
    - env: TOXENV=py34-dj111-wt111
      python: 3.4
    - env: TOXENV=py35-dj111-wt111
      python: 3.5


install:
  - pip install -U codecov tox
script:
  - tox
after_success:
  - codecov
