language: python
cache: pip

matrix:
  include:
    - env: TOXENV=py34-dj2-wt2
      python: 3.4
    - env: TOXENV=py35-dj2-wt2
      python: 3.5
    - env: TOXENV=py36-dj2-wt2
      python: 3.6

install:
  - pip install -U codecov tox
script:
  - tox
after_success:
  - codecov
