language: python
cache: pip

matrix:
  include:
  - env: TOXENV=py35-dj110-wt16
    python: 3.5
  - env: TOXENV=py34-dj110-wt16
    python: 3.4
  - env: TOXENV=py27-dj110-wt16
    python: 2.7
  - env: TOXENV=py35-dj19-wt16
    python: 3.5
  - env: TOXENV=py34-dj19-wt16
    python: 3.4
  - env: TOXENV=py27-dj19-wt16
    python: 2.7
  - env: TOXENV=py35-dj18-wt16
    python: 3.5
  - env: TOXENV=py34-dj18-wt16
    python: 3.4
  - env: TOXENV=py27-dj18-wt16
    python: 2.7
  - env: TOXENV=py35-dj110-wt15
    python: 3.5
  - env: TOXENV=py34-dj110-wt15
    python: 3.4
  - env: TOXENV=py27-dj110-wt15
    python: 2.7
  - env: TOXENV=py35-dj19-wt15
    python: 3.5
  - env: TOXENV=py34-dj19-wt15
    python: 3.4
  - env: TOXENV=py27-dj19-wt15
    python: 2.7
  - env: TOXENV=py35-dj18-wt15
    python: 3.5
  - env: TOXENV=py34-dj18-wt15
    python: 3.4
  - env: TOXENV=py27-dj18-wt15
    python: 2.7
  - env: TOXENV=py35-dj110-wt14
    python: 3.5
  - env: TOXENV=py34-dj110-wt14
    python: 3.4
  - env: TOXENV=py27-dj110-wt14
    python: 2.7
  - env: TOXENV=py35-dj19-wt14
    python: 3.5
  - env: TOXENV=py34-dj19-wt14
    python: 3.4
  - env: TOXENV=py27-dj19-wt14
    python: 2.7
  - env: TOXENV=py35-dj18-wt14
    python: 3.5
  - env: TOXENV=py34-dj18-wt14
    python: 3.4
  - env: TOXENV=py27-dj18-wt14
    python: 2.7

install:
  - pip install -U tox

script:
  tox
