sudo: false
language: python
cache: pip
dist: xenial

matrix:
  include:
    # Wagtail 2.3 LTS to cover support until 2.7
    - env: TOXENV=dj20-wagtail23-py34
      python: 3.4
    - env: TOXENV=dj20-wagtail23-py35
      python: 3.5
    - env: TOXENV=dj20-wagtail23-py36
      python: 3.6
    - env: TOXENV=dj21-wagtail23-py35
      python: 3.5
    - env: TOXENV=dj21-wagtail23-py36
      python: 3.6

    # Wagtail 2.7 LTS
    - env: TOXENV=dj20-wagtail27-py35
      python: 3.5
    - env: TOXENV=dj20-wagtail27-py36
      python: 3.6
    - env: TOXENV=dj20-wagtail27-py37
      python: 3.7
    - env: TOXENV=dj20-wagtail27-py38
      python: 3.8
    - env: TOXENV=dj21-wagtail27-py35
      python: 3.5
    - env: TOXENV=dj21-wagtail27-py36
      python: 3.6
    - env: TOXENV=dj21-wagtail27-py37
      python: 3.7
    - env: TOXENV=dj21-wagtail27-py38
      python: 3.8
    - env: TOXENV=dj22-wagtail27-py35
      python: 3.5
    - env: TOXENV=dj22-wagtail27-py36
      python: 3.6
    - env: TOXENV=dj22-wagtail27-py37
      python: 3.7
    - env: TOXENV=dj22-wagtail27-py38
      python: 3.8

    # Wagtail 2.8
    - env: TOXENV=dj21-wagtail28-py35
      python: 3.5
    - env: TOXENV=dj21-wagtail28-py36
      python: 3.6
    - env: TOXENV=dj21-wagtail28-py37
      python: 3.7
    - env: TOXENV=dj21-wagtail28-py38
      python: 3.8
    - env: TOXENV=dj22-wagtail28-py35
      python: 3.5
    - env: TOXENV=dj22-wagtail28-py36
      python: 3.6
    - env: TOXENV=dj22-wagtail28-py37
      python: 3.7
    - env: TOXENV=dj22-wagtail28-py38
      python: 3.8
    - env: TOXENV=dj30-wagtail28-py36
      python: 3.6
    - env: TOXENV=dj30-wagtail28-py37
      python: 3.7
    - env: TOXENV=dj30-wagtail28-py38
      python: 3.8

    # Wagtail 2.9
    - env: TOXENV=dj30-wagtail29-py36
      python: 3.6
    - env: TOXENV=dj30-wagtail29-py37
      python: 3.7
    - env: TOXENV=dj30-wagtail29-py38
      python: 3.8

    # Flake 8
    - env: TOXENV=flake8
      python: 3.8


install:
  - pip install -U codecov tox
script:
  - tox -e $TOXENV
after_success:
  - codecov
