name: test

on: [pull_request, push]

jobs:

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tox -e flake8
        run: tox
        env:
          TOXENV: flake8

  test:
    name: unittests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - toxenv: py38-dj32-wt40
            python-version: 3.8
          - toxenv: py38-dj32-wt41
            python-version: 3.8
          - toxenv: py38-dj40-wt40
            python-version: 3.8
          - toxenv: py38-dj40-wt41
            python-version: 3.8
          - toxenv: py38-dj41-wt40
            python-version: 3.8
          - toxenv: py38-dj41-wt41
            python-version: 3.8

          - toxenv: py39-dj32-wt40
            python-version: 3.9
          - toxenv: py39-dj32-wt41
            python-version: 3.9
          - toxenv: py39-dj40-wt40
            python-version: 3.9
          - toxenv: py39-dj40-wt41
            python-version: 3.9
          - toxenv: py39-dj41-wt40
            python-version: 3.9
          - toxenv: py39-dj41-wt41
            python-version: 3.9

          - toxenv: py310-dj32-wt40
            python-version: '3.10'
          - toxenv: py310-dj32-wt41
            python-version: '3.10'
          - toxenv: py310-dj40-wt40
            python-version: '3.10'
          - toxenv: py310-dj40-wt41
            python-version: '3.10'
          - toxenv: py310-dj41-wt40
            python-version: '3.10'
          - toxenv: py310-dj41-wt41
            python-version: '3.10'
          - toxenv: py310-dj41-wt42
            python-version: '3.10'
          - toxenv: py310-dj42-wt50
            python-version: '3.10'
          - toxenv: py310-dj42-wt51
            python-version: '3.10'
          - toxenv: py310-dj42-wt52
            python-version: '3.10'

          - toxenv: py311-dj41-wt40
            python-version: '3.11'
          - toxenv: py311-dj41-wt41
            python-version: '3.11'
          - toxenv: py311-dj41-wt42
            python-version: '3.11'
          - toxenv: py311-dj42-wt50
            python-version: '3.11'
          - toxenv: py311-dj42-wt51
            python-version: '3.11'
          - toxenv: py311-dj42-wt52
            python-version: '3.11'

          - toxenv: py312-dj41-wt52
            python-version: '3.12'
          - toxenv: py312-dj42-wt52
            python-version: '3.12'
          - toxenv: py312-dj50-wt52
            python-version: '3.12'

    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
            POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tox
        run: |
            tox
        env:
          DATABASE_HOST: localhost
          DATABASE_USER: postgres
          DATABASE_PASS: postgres
          TOXENV: ${{ matrix.toxenv }}
